name: Deploy Next.js App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }}" >> .env
          echo "NEXT_PUBLIC_VERCEL_URL=${{ secrets.NEXT_PUBLIC_VERCEL_URL }}" >> .env
          echo "NEXT_PUBLIC_GOOGLE_MAP=${{ secrets.NEXT_PUBLIC_GOOGLE_MAP }}" >> .env
          echo "VERCEL_URL=${{ secrets.VERCEL_URL }}" >> .env
          echo "URL=${{ secrets.URL }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./.next"
          target: "/home/altaf/project/malaysia-api"
          
      - name: Restart PM2 process
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            /home/altaf/sh/restart_pm2.sh